VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  require 'yaml'
  settings = YAML.load_file 'setting.yml'

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.enabled  = true
    config.proxy.http     = settings['proxy']['http']
    config.proxy.https    = settings['proxy']['https']
    config.proxy.no_proxy = settings['proxy']['no-proxy']
  end

  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.11.11"
  config.vm.provision "shell", :path => "provision.sh"
  config.vm.synced_folder "./workspace", "/home/vagrant/sync", disabled: true
  config.vm.synced_folder "./workspace", "/vagrant"

end